# Generated by Django 5.2.6 on 2025-09-23 18:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SpaceWeatherAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_code', models.CharField(help_text='Space Weather Message Code (например, WARK06)', max_length=20)),
                ('serial_number', models.CharField(help_text='Serial Number', max_length=10)),
                ('issue_time', models.DateTimeField(help_text='Issue Time UTC')),
                ('warning_type', models.CharField(help_text='Тип предупреждения', max_length=100)),
                ('valid_from', models.DateTimeField(blank=True, help_text='Valid From UTC', null=True)),
                ('valid_to', models.DateTimeField(blank=True, help_text='Valid To UTC', null=True)),
                ('warning_condition', models.CharField(blank=True, help_text='Warning Condition', max_length=50, null=True)),
                ('noaa_scale', models.CharField(blank=True, help_text='NOAA Scale (например, G2 - Moderate)', max_length=20, null=True)),
                ('full_message', models.TextField(help_text='Полный текст предупреждения')),
                ('potential_impacts', models.TextField(blank=True, help_text='Потенциальные воздействия', null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Время создания записи')),
                ('is_processed', models.BooleanField(default=True, help_text='Обработано ли предупреждение')),
            ],
            options={
                'verbose_name': 'Предупреждение космической погоды',
                'verbose_name_plural': 'Предупреждения космической погоды',
                'ordering': ['-issue_time'],
                'unique_together': {('message_code', 'serial_number', 'issue_time')},
            },
        ),
    ]
