# Generated by Django 5.2.6 on 2025-09-23 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='spaceweatheralert',
            name='begin_time',
            field=models.DateTimeField(blank=True, help_text='Время начала события', null=True),
        ),
        migrations.AddField(
            model_name='spaceweatheralert',
            name='description',
            field=models.TextField(blank=True, help_text='Описание события (переведенное)', null=True),
        ),
        migrations.AddField(
            model_name='spaceweatheralert',
            name='end_time',
            field=models.DateTimeField(blank=True, help_text='Время окончания события', null=True),
        ),
        migrations.AddField(
            model_name='spaceweatheralert',
            name='estimated_velocity',
            field=models.CharField(blank=True, help_text='Оценочная скорость', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='spaceweatheralert',
            name='maximum_time',
            field=models.DateTimeField(blank=True, help_text='Время максимума события', null=True),
        ),
        migrations.AlterField(
            model_name='spaceweatheralert',
            name='message_code',
            field=models.CharField(help_text='Space Weather Message Code', max_length=20),
        ),
    ]
