# Generated by Django 5.2.6 on 2025-09-23 23:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_spaceweatheralert_begin_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='spaceweatheralert',
            name='forecast_data',
            field=models.TextField(blank=True, help_text='Данные прогноза (для WATA20)', null=True),
        ),
        migrations.AddField(
            model_name='spaceweatheralert',
            name='maximum_flux',
            field=models.CharField(blank=True, help_text='Максимальный поток (для ALTEF3)', max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='TypeAForecastAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_code', models.CharField(help_text='Space Weather Message Code', max_length=20)),
                ('serial_number', models.CharField(help_text='Serial Number', max_length=10)),
                ('issue_time', models.DateTimeField(help_text='Issue Time UTC')),
                ('warning_type', models.CharField(help_text='Тип предупреждения', max_length=200)),
                ('full_message', models.TextField(help_text='Полный текст предупреждения')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Время создания записи')),
                ('is_processed', models.BooleanField(default=True, help_text='Обработано ли предупреждение')),
                ('forecast_data', models.TextField(blank=True, help_text='Данные прогноза', null=True)),
                ('potential_impacts', models.TextField(blank=True, help_text='Потенциальные воздействия', null=True)),
            ],
            options={
                'verbose_name': 'Прогноз геомагнитных бурь',
                'verbose_name_plural': 'Прогнозы геомагнитных бурь',
                'unique_together': {('message_code', 'serial_number', 'issue_time')},
            },
        ),
        migrations.CreateModel(
            name='TypeEElectronAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_code', models.CharField(help_text='Space Weather Message Code', max_length=20)),
                ('serial_number', models.CharField(help_text='Serial Number', max_length=10)),
                ('issue_time', models.DateTimeField(help_text='Issue Time UTC')),
                ('warning_type', models.CharField(help_text='Тип предупреждения', max_length=200)),
                ('full_message', models.TextField(help_text='Полный текст предупреждения')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Время создания записи')),
                ('is_processed', models.BooleanField(default=True, help_text='Обработано ли предупреждение')),
                ('begin_time', models.DateTimeField(blank=True, help_text='Время начала события', null=True)),
                ('maximum_flux', models.CharField(blank=True, help_text='Максимальный поток', max_length=100, null=True)),
                ('potential_impacts', models.TextField(blank=True, help_text='Потенциальные воздействия', null=True)),
            ],
            options={
                'verbose_name': 'Алерт потока электронов',
                'verbose_name_plural': 'Алерты потока электронов',
                'unique_together': {('message_code', 'serial_number', 'issue_time')},
            },
        ),
        migrations.CreateModel(
            name='TypeKGeomagneticAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_code', models.CharField(help_text='Space Weather Message Code', max_length=20)),
                ('serial_number', models.CharField(help_text='Serial Number', max_length=10)),
                ('issue_time', models.DateTimeField(help_text='Issue Time UTC')),
                ('warning_type', models.CharField(help_text='Тип предупреждения', max_length=200)),
                ('full_message', models.TextField(help_text='Полный текст предупреждения')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Время создания записи')),
                ('is_processed', models.BooleanField(default=True, help_text='Обработано ли предупреждение')),
                ('valid_from', models.DateTimeField(blank=True, help_text='Valid From UTC', null=True)),
                ('valid_to', models.DateTimeField(blank=True, help_text='Valid To UTC', null=True)),
                ('begin_time', models.DateTimeField(blank=True, help_text='Время начала события', null=True)),
                ('warning_condition', models.CharField(blank=True, help_text='Warning Condition', max_length=50, null=True)),
                ('noaa_scale', models.CharField(blank=True, help_text='NOAA Scale', max_length=20, null=True)),
                ('potential_impacts', models.TextField(blank=True, help_text='Потенциальные воздействия', null=True)),
            ],
            options={
                'verbose_name': 'Геомагнитный алерт K-индекса',
                'verbose_name_plural': 'Геомагнитные алерты K-индекса',
                'unique_together': {('message_code', 'serial_number', 'issue_time')},
            },
        ),
        migrations.CreateModel(
            name='TypeTRadioAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_code', models.CharField(help_text='Space Weather Message Code', max_length=20)),
                ('serial_number', models.CharField(help_text='Serial Number', max_length=10)),
                ('issue_time', models.DateTimeField(help_text='Issue Time UTC')),
                ('warning_type', models.CharField(help_text='Тип предупреждения', max_length=200)),
                ('full_message', models.TextField(help_text='Полный текст предупреждения')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Время создания записи')),
                ('is_processed', models.BooleanField(default=True, help_text='Обработано ли предупреждение')),
                ('begin_time', models.DateTimeField(blank=True, help_text='Время начала события', null=True)),
                ('estimated_velocity', models.CharField(blank=True, help_text='Оценочная скорость', max_length=100, null=True)),
                ('description', models.TextField(blank=True, help_text='Описание события', null=True)),
            ],
            options={
                'verbose_name': 'Алерт радиоизлучения типа II',
                'verbose_name_plural': 'Алерты радиоизлучения типа II',
                'unique_together': {('message_code', 'serial_number', 'issue_time')},
            },
        ),
    ]
