# Generated by Django 5.2.6 on 2025-09-24 07:46

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0003_spaceweatheralert_forecast_data_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(help_text='Имя автора комментария', max_length=100)),
                ('content', models.TextField(help_text='Текст комментария', max_length=1000)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Время создания комментария')),
                ('alert', models.ForeignKey(help_text='Предупреждение', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='weather.spaceweatheralert')),
            ],
            options={
                'verbose_name': 'Комментарий к предупреждению',
                'verbose_name_plural': 'Комментарии к предупреждениям',
                'ordering': ['-created_at'],
            },
        ),
    ]
